sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_REPO -f Dockerfile.dev . 

script:
  - docker run $DOCKER_REPO npm run test -- --coverage

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker build -f Dockerfile -t $COMMIT .
  - docker tag $COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "$TAG"
  - docker tag $COMMIT $DOCKER_REPO:$TAG
  - docker push $DOCKER_REPO:$TAG

